### ISSUE TITLE
Navigator is depreacated and removed

### ISSUE THREAD

**Issue by RameshkrishnanV** [aksonov/react-native-redux-router#25]
i'm facing issue navigator is depreacted and removed

SyntaxError: Unexpected end of JSON input
    at parse (native)
    at process._tickCallback (internal/process/next_tick.js:103:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1036:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Socket.Writable.end (_stream_writable.js:453:10)
    at Socket.end (net.js:423:31)
    at Promise.resolve.then.then.then.catch.then.message (D:\Ramesh krishnan\REACT-NATIVE\Redux_App\MyCommunity\node_modules\react-native\packager\src\Server\symbolicate\worker.js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE

**Comment by frayeralex** [comment]
Same issue:
![screenshot_2017-09-07-21-58-39-210_host exp exponent](https://user-images.githubusercontent.com/15966404/30180265-f68981aa-9417-11e7-9ad1-c744b4a2f640.png)

node: 6.11.0
npm: 4.6.1

```javascript
"devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.6.1",
    "eslint-plugin-flowtype": "^2.35.1",
    "eslint-plugin-react": "^7.3.0",
    "jest-expo": "~20.0.0",
    "react-native-scripts": "1.3.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "dependencies": {
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.0",
    "react-native-deprecated-custom-components": "^0.1.1",
    "react-native-redux-router": "^1.0.7",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }
```
